name: "Acquire Halo Infinite Match Data"

on:
  push:
  repository_dispatch:
  workflow_dispatch:
  schedule:
  - cron: '15 * * * *'
      
jobs:
  build:
    environment: Production
    runs-on: windows-latest
    name: Build
    env:
      SL_CLIENT_ID: ${{ secrets.SL_CLIENT_ID }}
      SL_CLIENT_SECRET: ${{ secrets.SL_CLIENT_SECRET }}
      SL_REFRESH_TOKEN: ${{ secrets.SL_REFRESH_TOKEN }}
      SL_ACCESS_TOKEN: ${{ secrets.SL_ACCESS_TOKEN }}
      SL_GITHUB_TOKEN: ${{ secrets.SL_GITHUB_TOKEN }}
      SL_BUILD_ID: ${{ secrets.SL_BUILD_ID }}
      SL_PROJECT_ID: ${{ secrets.SL_PROJECT_ID }}

    steps:
    - uses: actions/checkout@v2
    - name: Download StatLink
      run: Invoke-WebRequest https://github.com/dend/openspartan-statlink/releases/download/v0.1.0/ossl-windows-latest.zip -OutFile ossl-windows-latest.zip
    - name: Extract StatLink
      run: Expand-Archive -Path ossl-windows-latest.zip -DestinationPath _statlink
    - name: List content in the current folder
      run: ls
    - name: Log in to GitHub CLI
      run: Write-Output $Env:SL_GITHUB_TOKEN | gh auth login --with-token
    - name: Refresh token & store it
      run: |
        $data = . ${{ github.workspace }}\_statlink\finalbuild-windows-latest\OpenSpartan.StatLink.exe refresh --client-id $Env:SL_CLIENT_ID --client-secret $Env:SL_CLIENT_SECRET --redirect-url https://localhost --refresh-token $Env:SL_REFRESH_TOKEN | ConvertFrom-Json
        $repository="dend/openspartan-data-snapshots"
        gh secret set "SL_ACCESS_TOKEN" --env "Production" --body $data.AccessToken --repo $repository
        gh secret set "SL_REFRESH_TOKEN" --env "Production" --body $data.RefreshToken --repo $repository
    - name: Get data
      run: |
        . ${{ github.workspace }}\_statlink\finalbuild-windows-latest\OpenSpartan.StatLink.exe getstats --auth-token "$Env:SL_ACCESS_TOKEN" --build-id "$Env:SL_BUILD_ID" --project-id "$Env:SL_PROJECT_ID" --out "data"
    - name: Commit changes
      run: |
        git add -A -v
        git config --global user.name 'Den Delimarsky'
        git config --global user.email '1389609+dend@users.noreply.github.com'
        git commit -m "Updating snapshot with data."
        git push origin main
